version: '3'

services:

    app:
        build:
            context: ./node
        container_name: app
        command: node ./index.js
        networks:
            - node-network
        volumes:
            - ./node:/usr/src/app
        tty: true
    
    server:
        build: 
            context: ./nginx
        container_name: server
        networks:
            - node-network
        volumes:
            - ./html:/usr/share/nginx/html
            - ./nginx/conf:/etc/nginx/conf.d
        ports:
            - 8080:80
        
networks:
    node-network:
        driver: bridge